[package]
author = "Alexandria P."
name = "dynarg"
version = "2.1.5"
edition = "2021"
description = "A simple mechanism for dynamic robust argument handling"
license = "LGPL-3.0-or-later"
repository = "https://github.com/alxpettit/dynarg"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.9.2"
snafu = "0.7.4"
