[package]
author = "Alexandria P."
name = "dynarg"
version = "0.1.2"
edition = "2021"
description = "A simple mechanism for dynamic robust argument handling"
license = "AGPL-3.0-or-later"
repository = "https://github.com/alxpettit/dynarg"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
indexmap = "1.9.2"
